/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trasporte;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author josemanuel
 */
public class Registro_de_Fletes extends javax.swing.JFrame {

    /** *** 
     **
     * Esta son las variales que utilizo para el registro de los
     * fletes
     */
    protected String RFC;
    protected String ori_flete;
    protected String Desti_flete;
    protected String Flete_redondo="false";
    protected float volumeCarga;
    protected float peso;
    protected float Distancia;
    protected boolean redondo = false;
    protected float bas; 
    Operaciones total = new Operaciones();
    ConectarBd conex= new ConectarBd();
    Connection  conectar = conex.conexion();
   
    /**
     * Creates new form Registro_de_Fletes
     * 
     */
    public Registro_de_Fletes() {
        initComponents();
        /*** 
         **
         * octengo los datos de los clientes registrados         
         */
        OctenerRFC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(525, 525));
        setMinimumSize(new java.awt.Dimension(525, 525));
        setPreferredSize(new java.awt.Dimension(525, 525));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Registro de Fletes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 10, 190, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("RFC");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 60, 50, 15);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Origen del flete");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 70, 110, 15);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(400, 60, 105, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Destino del flete");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 110, 130, 15);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(120, 100, 104, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Volumen de la carga ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 110, 140, 15);

        jTextField4.setText("123254,98");
        jTextField4.setToolTipText("");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(400, 100, 62, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("peso");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 170, 70, 15);

        jTextField5.setText("215");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(120, 160, 170, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("flete redondo ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 170, 100, 15);

        jRadioButton1.setLabel("si");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(430, 160, 33, 23);

        jButton1.setLabel("volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 300, 63, 40);

        jButton2.setLabel("Ver Reportes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 300, 110, 40);

        jButton3.setLabel("Registrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(340, 300, 110, 40);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 51));
        jLabel8.setText("Distancia");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 210, 120, 15);

        jTextField6.setText("4512");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(120, 200, 82, 40);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setText("total $");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 210, 90, 15);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(390, 200, 82, 30);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(120, 60, 149, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/slide_3.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-20, -70, 560, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    /*
    ****
    *Este es el boton que hace el registro de los fletes
    */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:

            registro_de_fletes();
        } catch (SQLException ex) {
            Logger.getLogger(Registro_de_Fletes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
        /**** 
         **
         * Este es el radio buton que funciona como una badera si 
         * el flete es redondo on para calcular el precio
         */
    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
          if(jRadioButton1.isSelected()){
              
             redondo = jRadioButton1.isSelected();
             Flete_redondo="si";
            
        }
         else
               {
                   redondo = false;
                   Flete_redondo="no";
               }
    }//GEN-LAST:event_jRadioButton1MouseClicked
    /** 
     **
     * pasamos a la ventana de ver todos lo fletes que se an echo
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Ver_Reportes ver_reportes = new Ver_Reportes();
        ver_reportes.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
        /** 
         **
         * cerramos la ventana y seramos la conexion a la base de datos
         */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            conectar.close();
        } catch (SQLException ex) {
            Logger.getLogger(Registro_de_Fletes.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Fletes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Fletes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Fletes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Fletes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_de_Fletes().setVisible(true);
            }
        });
    }
/** 
 **
 * Este es el  metodo donde se realiza todas la operaciones 
 */
    public void registro_de_fletes() throws SQLException{
       
        
        if (conectar == null){
            JOptionPane.showMessageDialog(null,"Fallo la Conexion a la base de datos");
        }
        else{
            JOptionPane.showMessageDialog(null,"conexion  exitosa");
        }
        
        
        if (jTextField2.getText().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo de origen flete esta vacio");
            
            EXIT_ON_CLOSE(1);
        }
        else
        {
            ori_flete = jTextField2.getText();
        }
        
        if (jTextField3.getText().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo de destino fletes esta vacio");
            EXIT_ON_CLOSE(1);
        }
        else
        {
            Desti_flete = jTextField3.getText();
        }
        
        if (jTextField4.getText().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo de volumen de carga esta vacio");
            EXIT_ON_CLOSE(1);
        }
        else
        {
            volumeCarga = Float.parseFloat(jTextField4.getText());
        }
        if (jTextField5.getText().length() == 0){
            JOptionPane.showMessageDialog(null,"EL campo de el peso esta vacio");
            EXIT_ON_CLOSE(1);
        }
        else
        {
            peso = Float.parseFloat(jTextField5.getText());
        }
         if (jTextField6.getText().length() == 0){
            JOptionPane.showMessageDialog(null,"EL campo de la distancia esta vacio");
            EXIT_ON_CLOSE(1);
        }
        else
        {
            Distancia = Float.parseFloat(jTextField6.getText());
        }
         /** 
          **
          * Cremos un objeto de la clase operaciones para
          * calcular el precio
          */ 
        float gasto = total.costo(Distancia, volumeCarga, peso, redondo);
        String aux=Float.toString(gasto);
        jTextField7.setText(aux);
        
        bas = Float.parseFloat(jTextField7.getText());
         
         String slq="INSERT INTO fletes (id_RFC,origen,destino,volumen,peso,redondo,Precio) VALUE(?,?,?,?,?,?,?)";
        
        PreparedStatement guardar = conectar.prepareStatement(slq);
        guardar.setString(1, (String) jComboBox1.getSelectedItem());
        guardar.setString(2, ori_flete);
        guardar.setString(3, Desti_flete);
        guardar.setFloat(4, volumeCarga );
        guardar.setFloat(5, peso);
        guardar.setString(6, Flete_redondo);
        guardar.setFloat(7, bas);
        
        int n=guardar.executeUpdate();
        if (n > 0){
            JOptionPane.showMessageDialog(null,"SE ha ajendado correctamente");            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No se ha registrado");
        }
        
      
        
    }  
    /** 
     **
     * octengo el RFC de los clientes para su posterior registro de los fletes
     */
     public void OctenerRFC(){
    
           String sql="Select *from cliente";
        
        try {
            Statement octenerfc = conectar.createStatement();
               ResultSet resutado = octenerfc.executeQuery(sql);
               while (resutado.next()){
                   jComboBox1.addItem(resutado.getString("RFC"));
               }
             
             
        } catch (SQLException ex) {
            Logger.getLogger(ConectarBd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

    private void EXIT_ON_CLOSE(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
